version: "3.8"

services:
  lwo_db:
    image: mongo
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: "db"
    ports:
      - "27017:27017"
    volumes:
      - ./dbdata:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js
  
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lwo_webserver
    ports:
      - "${WEBSERVER_PORT}:8000"
